# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IMPORTING', 'Importing Data'), ('BUILDING', 'Building Network Graph'), ('CONNECTIVITY', 'Calculating Connectivity'), ('METRICS', 'Calculating Graph Metrics'), ('EXPORTING', 'Exporting Results'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='CREATED', max_length=12)),
                ('state_abbrev', localflavor.us.models.USStateField(help_text='The US state that the uploaded neighborhood is in', max_length=2)),
                ('neighborhood_file', models.FileField(help_text='A zipped shapefile boundary to run the bike network analysis on', upload_to='/')),
            ],
        ),
    ]
